version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4000:4000"
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    volumes:
      - .:/opt/app
      - build_cache:/opt/cache
      - $SSH_AUTH_SOCK:${SSH_AUTH_SOCK}
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file: .env.development
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - DISPLAY=${DISPLAY}
    tty: true
    stdin_open: true
    command: '/bin/bash -c "while true; do sleep 10; done;"'
    ulimits:
      nofile: 1024
      nproc: 63090
  db:
    image: postgres:12.4-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snitch_dev
    ports:
      - "5434:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
volumes:
  db: {}
  build_cache: {}
