# syntax=docker/dockerfile:experimental

FROM verybigthings/elixir:1.10.4

ARG APP_USER=user
ARG WORKDIR=/opt/app

ENV APP_USER=$APP_USER
ENV CACHE_DIR=/opt/cache
ENV BUILD_PATH=$CACHE_DIR/_build
ENV HEX_HOME=$CACHE_DIR/hex
ENV MIX_HOME=$CACHE_DIR/mix
ENV PHOENIX_VERSION 1.5.4
ENV REBAR_CACHE_DIR=$CACHE_DIR/rebar
ENV WORKDIR=$WORKDIR

RUN apt-get update && apt-get install -y \
  curl \
  gcc \
  git \
  libfontconfig1 \
  libxext6 \
  libxrender1 \
  locales \
  gnupg \
  make \
  postgresql-client \
  postgresql-contrib \
  vim \
  wget

RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
RUN tar vxf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
RUN cp wkhtmltox/bin/wk* /usr/local/bin/

WORKDIR $WORKDIR

RUN mix local.hex --force && mix local.rebar --force
RUN mix archive.install hex phx_new $PHOENIX_VERSION --force

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com > ~/.ssh/known_hosts

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash", "-c", "while true; do sleep 10; done;"]


