nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      - path: spec/containers/envFrom/secretRef/name
        version: v1
        kind: Pod
      - path: spec/initContainers/envFrom/secretRef/name
        version: v1
        kind: Pod
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/containers/envFrom/configMapRef/name
        version: v1
        kind: Pod
      - path: spec/initContainers/envFrom/configMapRef/name
        version: v1
        kind: Pod
  - kind: Service
    version: v1
    fieldSpecs:
      - path: spec/rules/http/paths/backend/serviceName
        version: v1
        kind: Ingress
