apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namePrefix: develop-
commonLabels:
  environment: develop
namespace: develop
configMapGenerator:
  - name: nue
    env: config.env
secretGenerator:
  - name: nue
    env: secrets.env
    type: Opaque
images:
  - name: docker.pkg.github.com/verybigthings/nue/nue
    newTag: replaceme
patchesJson6902:
  - path: patch/host.json
    target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: nue
