name: "Test, build & deploy - develop env"

on:
  push:
    branches:
      - develop
      - adapt-to-beanstalk

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "docker-compose.yml"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: nue-dev
          environment_name: nue-dev-env
          version_description: ${{ github.sha }}
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
