name: "TEST - run"

on:
  push:
    branches-ignore:
    - develop
    - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      CACHE_VERSION: v1
      AVIA_DOCS: avia_docs
      ADMIN_PORT: 4000
      API_PORT: 3000
      AWS_ACCESS_KEY_ID: api_key
      AWS_REGION: aws_region
      AWS_SECRET_ACCESS_KEY: secret_api_key
      BACKEND_URL: http://localhost:4000
      BUCKET_NAME: bucket_name
      DB_URL: postgres://postgres:postgres:@db/snitch_dev
      ELASTIC_HOST: http://localhost:9200/
      ETSY_CONSUMER_KEY: api_key
      ETSY_CONSUMER_SECRET: api_key
      FRONTEND_CHECKOUT_URL: frontend_checkout_url
      FRONTEND_URL: http://localhost:4200
      HOST: localhost
      HOSTED_PAYMENT_URL: hosted_payment_url
      PASSWORD_RESET_SALT: password_reset_salt
      POOL_SIZE: 10
      SENDGRID_API_KEY: api_key
      SENDGRID_SENDER_EMAIL: noreplay@nue.com
      SESSION_COOKIE_NAME: nue_session
      SESSION_COOKIE_SIGNING_SALT: session_cookie_salt
      SESSION_COOKIE_ENCRYPTION_SALT: session_cookie_encryption
      SUPPORT_URL: support_url
      SECRET_KEY_BASE: oZiDNlntvnC+q7EAIKVUV/AYTJ30UQZh/eUwcFK5h7As0Rhc6Zuf//0fvx9pMZUY
      TEST_DB_URL: postgres://postgres:postgres@localhost/snitch_test
      TOKEN_MAXIMUM_AGE: 36000
      WKHTML_PATH: /usr/local/bin/wkhtmltopdf
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3.4.2
          elixir-version: 1.10.4

      - name: Restore cached deps
        uses: actions/cache@v2
        with:
          path: |
            deps
             _build
          key: deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            deps-${{ env.CACHE_VERSION }}-
      - name: Run CI checks
        uses: ./.github/workflows/actions/test
        with:
          ssh-private-key: ${{ secrets.VBT_DEPLOY_SSH_PRIVATE_KEY }}
